import XCTest
@testable import PaywalloSDK

/// The vectors below were generated by RUNNING the React Native implementation
/// (`src/utils/uuid.ts`) over the same seeds. They are the contract between the two
/// SDKs: `installEventId` is derived from `"{appKey}:{stableKey}"` on both, and the
/// backend deduplicates installs on it — a divergence here silently turns one reinstall
/// into two installs in the data.
final class IdentityDeterministicUUIDTests: XCTestCase {

    private let vectors: [(seed: String, expected: String)] = [
        ("", "811c9dc5-8e13-42ca-9c7b-6d352bb6376f"),
        ("a", "e40c292c-53cf-4331-aacc-1b3cddd8ab0a"),
        ("0123456789", "f9808ff2-63d2-4df5-9206-a3e2a97d1114"),
        ("paywallo", "2637fbaa-92e6-44f5-9cab-677a76d0ab24"),
        ("appkey:idfv:1700000000000", "7b6eb404-bcdb-4cc1-a775-27741a31d75a"),
        (
            "app_key_123:ABCDEF01-2345-6789-ABCD-EF0123456789",
            "3bac019f-30c0-4378-a42e-856ff1f657c1"
        ),
        // Non-ASCII: proves the hash walks UTF-16 code units (`charCodeAt`), not bytes.
        ("café ☕", "2ad693d3-f7dc-4814-ac2e-e323542fcb35"),
        // Outside the BMP: one scalar, TWO UTF-16 units — hashing scalars diverges here.
        ("🎉", "682eae76-1beb-4991-af85-8506c3255260"),
        ("ab🎉cd", "ba57f7d6-9228-49e5-a19c-bd663dae9b70"),
    ]

    func testMatchesReactNativeVectors() {
        for vector in vectors {
            XCTAssertEqual(
                deterministicUUID(vector.seed),
                vector.expected,
                "seed \(vector.seed.debugDescription) diverged from the RN implementation"
            )
        }
    }

    func testIsDeterministic() {
        XCTAssertEqual(deterministicUUID("stable-seed"), deterministicUUID("stable-seed"))
    }

    func testDifferentSeedsProduceDifferentIds() {
        XCTAssertNotEqual(deterministicUUID("appkey:idfv-a"), deterministicUUID("appkey:idfv-b"))
    }

    func testOutputIsLowercase() {
        let id = deterministicUUID("app_key_123:ABCDEF01-2345-6789-ABCD-EF0123456789")
        XCTAssertEqual(id, id.lowercased())
    }

    /// StoreKit2's `appAccountToken` rejects anything that is not a strict UUID v4 —
    /// silently, with the webhook arriving with a null app_user_id.
    func testShapeIsUuidV4() {
        let pattern = "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
        for vector in vectors {
            let id = deterministicUUID(vector.seed)
            XCTAssertNotNil(
                id.range(of: pattern, options: .regularExpression),
                "\(id) is not a valid UUID v4"
            )
        }
    }
}
